using OmopTransformer.Annotations;

namespace OmopTransformer.Transformation;

[Description("CARE PROFESSIONAL MAIN SPECIALTY CODE (DIAGNOSIS)")]
internal class CareProfessionalMainSpecialtyCodeDiagnosisLookup : ILookup
{
    public Dictionary<string, ValueWithNote> Mappings { get; } =
        new()
        {
            { "100", new ValueWithNote(null, "General Surgery") },
            { "101", new ValueWithNote(null, "Urology") },
            { "107", new ValueWithNote(null, "Vascular Surgery") },
            { "110", new ValueWithNote(null, "Trauma and Orthopaedics") },
            { "120", new ValueWithNote(null, "Ear Nose and Throat") },
            { "130", new ValueWithNote(null, "Ophthalmology") },
            { "140", new ValueWithNote(null, "Oral Surgery") },
            { "141", new ValueWithNote(null, "Restorative Dentistry") },
            { "142", new ValueWithNote(null, "Paediatric Dentistry") },
            { "143", new ValueWithNote(null, "Orthodontics") },
            { "145", new ValueWithNote(null, "Oral and Maxillofacial Surgery") },
            { "146", new ValueWithNote(null, "Endodontics") },
            { "147", new ValueWithNote(null, "Periodontics") },
            { "148", new ValueWithNote(null, "Prosthodontics") },
            { "149", new ValueWithNote(null, "Surgical Dentistry") },
            { "150", new ValueWithNote(null, "Neurosurgery") },
            { "160", new ValueWithNote(null, "Plastic Surgery") },
            { "170", new ValueWithNote(null, "Cardiothoracic Surgery") },
            { "171", new ValueWithNote(null, "Paediatric Surgery") },
            { "180", new ValueWithNote(null, "Emergency Medicine") },
            { "190", new ValueWithNote(null, "Anaesthetics") },
            { "191", new ValueWithNote(null, "Pain Management (Retired 1 April 2004)") },
            { "192", new ValueWithNote(null, "Intensive Care Medicine") },
            { "200", new ValueWithNote(null, "Aviation and Space Medicine") },
            { "300", new ValueWithNote(null, "General Internal Medicine") },
            { "301", new ValueWithNote(null, "Gastroenterology") },
            { "302", new ValueWithNote(null, "Endocrinology and Diabetes") },
            { "303", new ValueWithNote(null, "Clinical Haematology") },
            { "304", new ValueWithNote(null, "Clinical Physiology") },
            { "305", new ValueWithNote(null, "Clinical Pharmacology") },
            { "310", new ValueWithNote(null, "Audio Vestibular Medicine") },
            { "311", new ValueWithNote(null, "Clinical Genetics") },
            { "312", new ValueWithNote(null, "Clinical Cytogenetics and Molecular Genetics (Retired 1 April 2010; code retained for consultants qualified before that date)") },
            { "313", new ValueWithNote(null, "Clinical Immunology") },
            { "314", new ValueWithNote(null, "Rehabilitation Medicine") },
            { "315", new ValueWithNote(null, "Palliative Medicine") },
            { "317", new ValueWithNote(null, "Allergy") },
            { "320", new ValueWithNote(null, "Cardiology") },
            { "321", new ValueWithNote(null, "Paediatric Cardiology") },
            { "325", new ValueWithNote(null, "Sport and Exercise Medicine") },
            { "326", new ValueWithNote(null, "Acute Internal Medicine") },
            { "330", new ValueWithNote(null, "Dermatology") },
            { "340", new ValueWithNote(null, "Respiratory Medicine") },
            { "350", new ValueWithNote(null, "Infectious Diseases") },
            { "352", new ValueWithNote(null, "Tropical Medicine") },
            { "360", new ValueWithNote(null, "Genitourinary Medicine") },
            { "361", new ValueWithNote(null, "Renal Medicine") },
            { "370", new ValueWithNote(null, "Medical Oncology") },
            { "371", new ValueWithNote(null, "Nuclear Medicine") },
            { "400", new ValueWithNote(null, "Neurology") },
            { "401", new ValueWithNote(null, "Clinical Neurophysiology") },
            { "410", new ValueWithNote(null, "Rheumatology") },
            { "420", new ValueWithNote(null, "Paediatrics") },
            { "421", new ValueWithNote(null, "Paediatric Neurology") },
            { "430", new ValueWithNote(null, "Geriatric Medicine") },
            { "450", new ValueWithNote(null, "Dental Medicine") },
            { "451", new ValueWithNote(null, "Special Care Dentistry") },
            { "460", new ValueWithNote(null, "Medical Ophthalmology") },
            { "500", new ValueWithNote(null, "Obstetrics and Gynaecology (not acceptable for central returns including Hospital Episode Statistics)") },
            { "501", new ValueWithNote(null, "Obstetrics") },
            { "502", new ValueWithNote(null, "Gynaecology") },
            { "504", new ValueWithNote(null, "Community Sexual and Reproductive Health") },
            { "510", new ValueWithNote(null, "Antenatal Clinic (Retired 1 April 2004)") },
            { "520", new ValueWithNote(null, "Postnatal Clinic (Retired 1 April 2004)") },
            { "560", new ValueWithNote(null, "Midwifery") },
            { "600", new ValueWithNote(null, "General Medical Practice") },
            { "601", new ValueWithNote(null, "General Dental Practice") },
            { "610", new ValueWithNote(null, "Maternity Function (Retired 1 April 2004)") },
            { "620", new ValueWithNote(null, "Other than Maternity (Retired 1 April 2004)") },
            { "700", new ValueWithNote(null, "Learning Disability") },
            { "710", new ValueWithNote(null, "Adult Mental Illness") },
            { "711", new ValueWithNote(null, "Child and Adolescent Psychiatry") },
            { "712", new ValueWithNote(null, "Forensic Psychiatry") },
            { "713", new ValueWithNote(null, "Medical Psychotherapy") },
            { "715", new ValueWithNote(null, "Old Age Psychiatry") },
            { "800", new ValueWithNote(null, "Clinical Oncology") },
            { "810", new ValueWithNote(null, "Radiology") },
            { "820", new ValueWithNote(null, "General Pathology") },
            { "821", new ValueWithNote(null, "Blood Transfusion") },
            { "822", new ValueWithNote(null, "Chemical Pathology") },
            { "823", new ValueWithNote(null, "Haematology") },
            { "824", new ValueWithNote(null, "Histopathology") },
            { "830", new ValueWithNote(null, "Immunopathology") },
            { "831", new ValueWithNote(null, "Medical Microbiology and Virology") },
            { "832", new ValueWithNote(null, "Neuropathology (Retired 1 April 2004)") },
            { "833", new ValueWithNote(null, "Medical Microbiology") },
            { "834", new ValueWithNote(null, "Medical Virology") },
            { "900", new ValueWithNote(null, "Community Medicine") },
            { "901", new ValueWithNote(null, "Occupational Medicine") },
            { "902", new ValueWithNote(null, "Community Health Services Dental") },
            { "903", new ValueWithNote(null, "Public Health Medicine") },
            { "904", new ValueWithNote(null, "Public Health Dental") },
            { "950", new ValueWithNote(null, "Nursing") },
            { "960", new ValueWithNote(null, "Allied Health Professional") },
            { "990", new ValueWithNote(null, "Joint Consultant Clinics (Retired 1 April 2004)") },
            { "199", new ValueWithNote(null, "Non-UK provider; specialty function not known, treatment mainly surgical") },
            { "499", new ValueWithNote(null, "Non-UK provider; specialty function not known, treatment mainly medical") },
        };

    public string[] ColumnNotes => Array.Empty<string>();
}
