using OmopTransformer.Annotations;

namespace OmopTransformer.Transformation;

[Description("MULTIDISCIPLINARY TEAM MEETING TYPE (CANCER)")]
internal class MultidisciplinaryTeamMeetingTypeCancerLookup : ILookup
{
    public Dictionary<string, ValueWithNote> Mappings { get; } =
        new()
        {
            { "0100", new ValueWithNote(null, "Breast") },
            { "0101", new ValueWithNote(null, "Breast Multidisciplinary Team Meeting") },
            { "0102", new ValueWithNote(null, "Metastatic Breast Multidisciplinary Team Meeting") },
            { "0200", new ValueWithNote(null, "Brain/Central Nervous System") },
            { "0201", new ValueWithNote(null, "Brain / Central Nervous System (CNS)/Neuroscience Multidisciplinary Team Meeting") },
            { "0202", new ValueWithNote(null, "Rehabilitation and Non-Surgical (Network) Multidisciplinary Team Meeting") },
            { "0203", new ValueWithNote(null, "Pituitary Multidisciplinary Team Meeting") },
            { "0204", new ValueWithNote(null, "Skull base Multidisciplinary Team Meeting") },
            { "0205", new ValueWithNote(null, "Spinal cord Multidisciplinary Team Meeting") },
            { "0206", new ValueWithNote(null, "Low grade glioma Multidisciplinary Team Meeting") },
            { "0207", new ValueWithNote(null, "Metastasis to brain Multidisciplinary Team Meeting") },
            { "0208", new ValueWithNote(null, "Stereotactic Radiosurgery (SRS) Multidisciplinary Team Meeting") },
            { "0209", new ValueWithNote(null, "Genetic subtypes Multidisciplinary Team Meeting") },
            { "0300", new ValueWithNote(null, "Colorectal") },
            { "0301", new ValueWithNote(null, "Colorectal Multidisciplinary Team Meeting") },
            { "0302", new ValueWithNote(null, "Anal Multidisciplinary Team Meeting") },
            { "0400", new ValueWithNote(null, "Children, Teenagers and Young Adults (CTYA)") },
            { "0401", new ValueWithNote(null, "Paediatric Combined Diagnostic and Treatment Multidisciplinary Team Meeting") },
            { "0402", new ValueWithNote(null, "Paediatric Haematology only Multidisciplinary Team Meeting") },
            { "0403", new ValueWithNote(null, "Paediatric non-Central Nervous System (CNS) solid tumours only Multidisciplinary Team Meeting") },
            { "0404", new ValueWithNote(null, "Paediatric Central Nervous System (CNS) malignancy only Multidisciplinary Team Meeting") },
            { "0405", new ValueWithNote(null, "Paediatric Late Effects Multidisciplinary Team Meeting") },
            { "0406", new ValueWithNote(null, "Paediatric Oncology Shared Care Unit (POSCU) Multidisciplinary Team Meeting") },
            { "0407", new ValueWithNote(null, "Teenage and Young Adult Multidisciplinary Team Meeting") },
            { "0408", new ValueWithNote(null, "Teenage and Young Adult Late Effects Multidisciplinary Team Meeting") },
            { "0500", new ValueWithNote(null, "Gynaecology") },
            { "0501", new ValueWithNote(null, "Gynaecology Local Multidisciplinary Team Meeting") },
            { "0502", new ValueWithNote(null, "Gynaecology Specialist Multidisciplinary Team Meeting") },
            { "0600", new ValueWithNote(null, "Haematology") },
            { "0601", new ValueWithNote(null, "Haematology Multidisciplinary Team Meeting") },
            { "0602", new ValueWithNote(null, "Lymphoma Multidisciplinary Team Meeting") },
            { "0603", new ValueWithNote(null, "Plasma Cell Multidisciplinary Team Meeting") },
            { "0604", new ValueWithNote(null, "Myeloid Multidisciplinary Team Meeting") },
            { "0605", new ValueWithNote(null, "Bone Marrow Transplant Multidisciplinary Team Meeting") },
            { "0700", new ValueWithNote(null, "Head and Neck (including Thyroid)") },
            { "0701", new ValueWithNote(null, "Upper Aerodigestive Tract (UAT) only Multidisciplinary Team Meeting") },
            { "0702", new ValueWithNote(null, "Upper Aerodigestive Tract (UAT) and Thyroid Multidisciplinary Team Meeting") },
            { "0703", new ValueWithNote(null, "Thyroid Only Multidisciplinary Team Meeting") },
            { "0800", new ValueWithNote(null, "Lung") },
            { "0801", new ValueWithNote(null, "Lung Multidisciplinary Team Meeting") },
            { "0802", new ValueWithNote(null, "Mesothelioma Specialist Multidisciplinary Team Meeting") },
            { "0900", new ValueWithNote(null, "Sarcoma") },
            { "0901", new ValueWithNote(null, "Bone and Soft tissue Multidisciplinary Team Meeting") },
            { "0902", new ValueWithNote(null, "Bone Multidisciplinary Team Meeting") },
            { "0903", new ValueWithNote(null, "Soft tissue Multidisciplinary Team Meeting") },
            { "1000", new ValueWithNote(null, "Skin") },
            { "1001", new ValueWithNote(null, "Skin Local Multidisciplinary Team Meeting") },
            { "1002", new ValueWithNote(null, "Skin Specialist Multidisciplinary Team Meeting") },
            { "1003", new ValueWithNote(null, "Melanoma Multidisciplinary Team Meeting") },
            { "1004", new ValueWithNote(null, "Supra T-Cell Lymphoma Multidisciplinary Team Meeting") },
            { "1100", new ValueWithNote(null, "Upper Gastrointestinal (GI)") },
            { "1101", new ValueWithNote(null, "Upper Gastrointestinal (GI) Local Multidisciplinary Team Meeting") },
            { "1102", new ValueWithNote(null, "Oesophago-Gastric (OG) Specialist Multidisciplinary Team Meeting") },
            { "1103", new ValueWithNote(null, "Hepatobiliary and Pancreatic (HPB) Multidisciplinary Team Meeting") },
            { "1104", new ValueWithNote(null, "Pancreatic/Biliary (PB) Specialist Multidisciplinary Team Meeting") },
            { "1105", new ValueWithNote(null, "Hepatic Specialist Multidisciplinary Team Meeting") },
            { "1200", new ValueWithNote(null, "Urology") },
            { "1201", new ValueWithNote(null, "Urology Local Multidisciplinary Team Meeting") },
            { "1202", new ValueWithNote(null, "Urology Specialist Multidisciplinary Team Meeting") },
            { "1203", new ValueWithNote(null, "Testicular Supranetwork Multidisciplinary Team Meeting") },
            { "1204", new ValueWithNote(null, "Penile Supranetwork Multidisciplinary Team Meeting") },
            { "1300", new ValueWithNote(null, "Other (not listed)") },
            { "1301", new ValueWithNote(null, "Cancer of Unknown Primary (CUP) Multidisciplinary Team Meeting") },
            { "1302", new ValueWithNote(null, "Neuroendocrine Multidisciplinary Team Meeting") },
            { "1303", new ValueWithNote(null, "Palliative Care Multidisciplinary Team Meeting") },
            { "1304", new ValueWithNote(null, "Enhanced Supportive Care Multidisciplinary Team Meeting") },
            { "1305", new ValueWithNote(null, "Stereotactic Radiotherapy (SRT) only (all sites) Multidisciplinary Team Meeting") },
            { "1306", new ValueWithNote(null, "Adrenal Multidisciplinary Team Meeting") },
        };

    public string[] ColumnNotes => Array.Empty<string>();
}
